config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'

  resources :trips do
  	resources :locations do
 		resources :addresses
 	end
 end
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :location
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :trip
	has_one :address
	
end

app/models/trip.rb
class Trip < ApplicationRecord
	has_many :locations
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_trip
  before_action :set_location
  before_action :set_address, except: [:index, :new, :create]


  def index
    @addresses = @location.addresses
  end

  def show
  end

  def new
    @address = @location.addresses.new
  end

  def create
    @address = @location.addresses.new(address_params)
    if @address.save
      redirect_to  trip_location_address_path(@trip, @location, @address)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to trip_location_address_path(@trip, @location, @address)
    else
      render :edit
    end
  end

  def destroy
    @address.destroy
    redirect_to trip_location_addresses_path(@trip, @location)
  end

  private
  def address_params
    params.require(:address).permit(:country, :city,
                                      :state, :zip, :location_id) 
  end

  def set_location
    @location = Location.find(params[:location_id])
  end

  def set_address
    @address = Address.find(params[:id])
    # @address = Address.find_by(id: params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_trip
  before_action :set_location, except: [:index, :new, :create]

  def index
    @locations = @trip.locations
  end

  def show
  end

  def new
    @location = @trip.locations.new
  end

  def create
    @location = @trip.locations.new(location_params)
    if @location.save
      redirect_to trip_location_path(@trip, @location)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to trip_location_path(@trip, @location)
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to trip_location_path(@trip)
  end

  private

  def location_params
    params.require(:location).permit(:name, :description)
  end

  def set_trip
    @trip = Trip.find(params[:trip_id])
  end

  def set_location
    @location = @trip.locations.find(params[:id])
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	before_action :set_trip, except: [:index, :new, :create]

  def index
  	@trips = Trip.all
  end

  def show
  end

  def new
  	@trip = Trip.new
  end

  def create
  	@trip = Trip.new(trip_params)
  	if @trip.save
  		redirect_to trip_path(@trip)
  	else
  		render :save
  	end
  end 

  def edit
  end

  def update
  	if @trip.update(trip_params)
  		redirect_to trip_path(@trip)
	else
		render :edit
  	end
  end

  def destroy
  	@trip.destroy
  	redirect_to trips_path
  end

  private
  def trip_params
  	params.require(:trip).permit(:title, :length, :expense, :date)
  end

  def set_trip
  	@trip = Trip.find(params[:id])
  end

end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/trip_helper.rb
module TripHelper
end

app/views/addresses/_form.html.erb
<h1> Create New Address </h1>
<%= form_for @address do |f| %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <br />

  <%= f.label :state %>
  <%= f.text_field :state %>
  <br />

  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <br />

  <%= f.label :country %>
  <%= f.text_field :country %>
  <br />
   

  <%= f.submit %>
<% end %>

app/views/addresses/edit.html.erb
<h1>Address#edit</h1>
<p>Find me in app/views/address/edit.html.erb</p>

app/views/addresses/new.html.erb
<h1> Addresses </h1>

<%= render(partial: 'form') %>

app/views/addresses/show.html.erb
<h1> Address:</h1>

<% if @address.city %>
	<p>City: <%= @address.city %> </p>
<% end %>

<% if @address.state %>
	<p>State: <%= @address.state %> </p>
<% end %>

<% if @address.zip %>
	<p>Zip: <%= @address.zip %> </p>
<% end %>

<% if @address.country %>
	<p>Country: <%= @address.country %> </p>
<% end %>

<%= link_to '' %>

<%= link_to 'All Locations', trip_locations_path(@location.trip) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripTrackr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<% if @location.errors.any? %>
  <h5> <%= pluralize(@location.errors.count, 'Error', 'Errors') %> Creating location </h5>
  <ul>
    <% @location.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
    <% end %>
  </ul>
<% end %>


<%= form_for [@trip, @location] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br />

	<%= f.label :description %>
	<%= f.text_field :description %>
	<br />

	<%= f.submit %>
<% end %>	

app/views/locations/edit.html.erb
<h1> Edit <%= @location.name %> </h1>

<%= render(partial: 'form') %>

<%= link_to 'Locations', trip_locations_path(@trip, @location) %>

app/views/locations/index.html.erb
<h1> <%= @trip.title %> Locations </h1>
<br />

<% if  @locations.any?  %>
	<% @locations.each do |location| %>
	<div>
		<%= link_to location.name, trip_location_path(@trip, location) %>
		</div>
	<% end %>
<% else %>	
<h5> No Locations, Please Add One</h5>
<% end %>

<hr />

<%= link_to 'New Location', new_trip_location_path(@trip) %>

<br />

<%= link_to "#{@trip.title}", trip_path(@trip) %>

app/views/locations/new.html.erb
<h1> <%= @trip.title %> New Location </h1>

<%= render(partial: 'form') %>

app/views/locations/show.html.erb
<h1> <%= @location.name %> </h1>
<br />

<%= link_to("Edit", edit_trip_location_path(@trip, @location)) %> |
<%= link_to("Delete", trip_location_path(@trip, @location), method: :delete, data: {confirm: 'Really Delete?'}) %>

<hr />

<p> <%= @location.description %> </p>

<%=  %>



<%= link_to "#{@location.name}'s Address", trip_location_addresses_path(@trip, @location) %>

app/views/trips/_form.html.erb
<% if @trip.errors.any? %>
	<h5> <% pluralize(@trip.errors.count, 'Error', 'Errors') %> Creating trip </h5>
	<ul>
		<%= @trip.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>
	</ul>
<% end %>



<%= form_for @trip do |f| %>
	<%= f.label :title %>:
	<%= f.text_field :title %>
	<br />

	<%= f.label :date %>
	<%= f.text_field :date %>
	<br />

	<%= f.label :length %>
	<%= f.text_field :length %>
	<br />

	<%= f.label :expense %>
	<%= f.text_field :expense %>
	<br />

	<%= f.submit %>
<% end %>
	<br />

	<%= link_to 'Back', trips_path %>

app/views/trips/edit.html.erb
<h1> Edit <%= @trip.title %> </h1>


<%= render(partial: 'form') %>

app/views/trips/index.html.erb
<h1> All Trips </h1>
<br />

<% if @trips.any? %>
	<ul>
		<% @trips.each do |trip| %>
			<li>
				<%= link_to trip.title, trip_path(trip) %> |
				<%= link_to 'Edit', edit_trip_path(trip) %> |
				<%= link_to 'Delete', trip_path(trip), method: :delete, data: {confirm: 'Really delete?'} %> 
			</li>
		<% end %>
	</ul>
	<% else %>
	<h3> Create a trip! </h3>
<% end %>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1> Create New Trip </h1>

<%= render(partial: 'form') %>

app/views/trips/show.html.erb
<h1> <%= @trip.title %> </h1>
<br />

<% if @trip.date %>
	<p>Date: <%= @trip.date %> </p>
<% end %>

<% if @trip.length %>
	<p>Length: <%= @trip.length %> </p>
<% end %>

<% if @trip.expense %>
	<p>Expense: <%= @trip.expense %> </p>
<% end %>

<div>
	<%= link_to "#{@trip.title.pluralize} Locations",
		trip_locations_path(@trip) %> |

	<%= link_to 'All Trips', trips_path %>
</div>